name: refresh content
permissions:
  contents: write

on:
  schedule:
  - cron: "0 11 * * 1"

jobs:
  getdataandrefreshtable:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8 #install the python needed
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: execute main.py
        run: |
          python main.py
      - name : push to master
        run: |
          date > generated.txt
          git fetch 
          git pull origin master
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push -f origin master
